spring:
    batch:
        job:
            enabled: false
        initialize-schema: always     
        commit:
            chunk: 2      
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:file:/home/rakesh/MyWorks/Stackoverflow/springBatchLocalParition/h2db/ngecomdb
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
thread:
  maxPool:
      size: 20
  corePool:
      size: 5
  queuePool:
      size:  5
